### ISSUE TITLE
请问如何将这个view放在屏幕右侧呢？

### ISSUE THREAD

**Issue by wizos** [ChenTianSaber/SlideBack#1]
我想把这个效果放在右侧，请问怎么可以做到呢？谢谢

**Comment by ChenTianSaber** [comment]
你好，
目前并没有做屏幕右侧的支持
如果你有这个需求的话，可以自己修改SlideBackView中绘制View的坐标和方向，以及SlideBackActivity监听的坐标
后续可以考虑做这个设置
