### ISSUE TITLE
底部边缘的侧滑位置，侧滑View 显示位置错误

### ISSUE THREAD

**Issue by truesA** [ChenTianSaber/SlideBack#3]
手指放到手机底部的侧滑位置（比如左边缘底部去侧滑）侧滑View 位置不对（位置跑到了顶部）

**Comment by truesA** [comment]
public void setBackViewY(View view, int y) {
        //判断是否超出了边界
        int topMargin = y - dp2px(SlideBackView.height) / 2;
       //注释掉这层边缘判断就好了
//        if (topMargin < 0 || y > screenHeight - dp2px(SlideBackView.height) / 2) {
//            return;
//        }
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(view.getLayoutParams());
        layoutParams.topMargin = topMargin;
        view.setLayoutParams(layoutParams);
       
    }

**Comment by ChenTianSaber** [comment]
您好，感谢您的反馈，您可以更新到0.8.2版本，已经修复了这个问题，谢谢！
